[package]
name = "ubungen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
text_io = "0.1.12"
serde = "1.0.144"
serde_derive = "1.0.144"
serde_json = "1.0.83"

